### ISSUE TITLE
tnt.posta.hr više nema DNS record

### ISSUE THREAD

**Issue by biuklija** [mnalis/ips_posta_hr#1]
Od 8.1.2021. tnt.posta.hr više nema DNS record. 
Alternativna rješenja za povlačenje podataka mogla bi biti: 

1. API Chrome proširenja (`curl -L "https://www.posta.hr/chrome.aspx" -d "query=LE00000000CN&vrsta=1" `)
2. https://posiljka.posta.hr/ koji *možda* ima Recaptchu.

**Comment by mnalis** [comment]
tnx na prijavi... probao sam samo izmijeniti URL, ali nemam trenutno niti jedan paket sa trackingom za test... imas mozda neki tracking koji ispisuje podatke za poslati mi na mail?

**Comment by biuklija** [comment]
Poslao sam ti nekoliko komada na mail.

**Comment by Anton700** [comment]
Zna netko DNS koji se koristio? Navodno ručnim dodavanjem u hosts file može opet raditi.
195.182.46.123 od posiljke.* nije, on izbaci 404.

**Comment by mnalis** [comment]
Evo stavio sam da se koristi navedeni JSON API. 
Javite da li vam radi OK.

**Comment by mnalis** [comment]
BTW zahtjeva novi perl modul JSON (na Debianu `apt-get install libjson-perl` ako nije instaliran)
