### ISSUE TITLE
Ukinuta Chrome ekstenzija

### ISSUE THREAD

**Issue by biuklija** [mnalis/ips_posta_hr#2]
Hrvatska pošta je ukinula svoju Chrome ekstenziju sa Chrome storea, a i API endpoint koji se koristio nakon ukidanja tnt.posta.hr.
Kako je server tnt.posta.hr i dalje živ, samo nema DNS IP entry, predlažem revert na njega uz hardkodirani IP 195.182.46.5, jer nudi detaljnije podatke o trackingu od posiljka.posta.hr.

**Comment by mnalis** [comment]
Složeno tako, sa `tnt.posta.hr` = `195.182.46.5`
